# Generated by Django 4.2.11 on 2024-05-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='record_id',
            new_name='id',
        ),
    ]
