# Generated by Django 4.2.11 on 2024-04-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_department_record_user_record_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='record',
            name='image_url',
        ),
        migrations.AddField(
            model_name='record',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.png', upload_to=''),
        ),
    ]
