# Generated by Django 4.2.11 on 2024-05-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.UUIDField(default='c4fa20c0c79a4aa99d51eb632c6b3f12', editable=False, primary_key=True, serialize=False),
        ),
    ]
