# Generated by Django 4.2.11 on 2024-05-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x00000205B799AC10>', editable=False, primary_key=True, serialize=False),
        ),
    ]
