# Generated by Django 4.2.11 on 2024-05-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.UUIDField(default='eef6bf2af07545d6a4d07b0b1db61b06', editable=False, primary_key=True, serialize=False),
        ),
    ]
