# Generated by Django 4.2.11 on 2024-05-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.CharField(default='b0f54f5421124a5da66cb389f03bfaad', max_length=100, primary_key=True, serialize=False),
        ),
    ]
