# Generated by Django 4.2.11 on 2024-05-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.CharField(default='f2462db8-9d40-4236-83bd-5b41b61afb65', max_length=100, primary_key=True, serialize=False),
        ),
    ]
