# Generated by Django 4.2.11 on 2024-05-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.CharField(default='c65b60ef5b4d47428a161c42f8e5fc83', max_length=100, primary_key=True, serialize=False),
        ),
    ]
