# Generated by Django 4.2.11 on 2024-05-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(default='8b6568edf9c44764a47fc3a02b681ac9', primary_key=True, serialize=False),
        ),
    ]
