# Generated by Django 4.2.11 on 2024-05-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(default='55782fc25e8644bdb0d8e27fa17dd30f', max_length=36, primary_key=True, serialize=False),
        ),
    ]
