# Generated by Django 4.2.11 on 2024-05-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_alter_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_id',
            field=models.CharField(default='7c86568dec534af4a5ded420c8d27f8b', max_length=36),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
