# Generated by Django 4.2.11 on 2024-05-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_record_record_id_alter_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_id',
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.CharField(default='REG0759', max_length=36, primary_key=True, serialize=False),
        ),
    ]
