# Generated by Django 4.2.11 on 2024-05-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_remove_record_record_id_alter_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.AddField(
            model_name='record',
            name='record_id',
            field=models.CharField(default='0d5b93a8149f4b5c807bc0927568920d', max_length=36, primary_key=True, serialize=False),
        ),
    ]
