# Generated by Django 4.2.11 on 2024-05-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_remove_record_id_record_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.CharField(default='db923f656c374b9790b7c58e6fac14e3', max_length=36, primary_key=True, serialize=False),
        ),
    ]
