# Generated by Django 4.2.11 on 2024-05-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_alter_record_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.CharField(default='ef02dc6369f343c784d80a6486c29568', max_length=36, primary_key=True, serialize=False),
        ),
    ]
