# Generated by Django 4.2.11 on 2024-05-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_alter_record_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='unique_id',
            field=models.CharField(blank=True, default='REG317498', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.CharField(default='81e2d6b8fd1e43f5bbce8d9dc09f8094', max_length=36, primary_key=True, serialize=False),
        ),
    ]
