# Generated by Django 4.2.11 on 2024-05-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_record_unique_id_alter_record_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.CharField(default='0fe04cd34ab640e083afabbe03789290', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='unique_id',
            field=models.CharField(blank=True, default='REG449265', max_length=6, null=True),
        ),
    ]
