# Generated by Django 4.2.11 on 2024-05-03 03:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_alter_record_record_id_alter_record_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.UUIDField(default=uuid.UUID('2fde02ae-fc3e-4303-94e1-43305dced094'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='unique_id',
            field=models.CharField(blank=True, default='REG663517', max_length=6, null=True),
        ),
    ]
