# Generated by Django 4.2.11 on 2024-05-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_alter_record_record_id_alter_record_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.UUIDField(default='709b60019746400c9bb52d39b36d838b', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='unique_id',
            field=models.CharField(blank=True, default='REG447252', max_length=6, null=True),
        ),
    ]
