# Generated by Django 4.2.11 on 2024-05-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0026_remove_record_unique_id_alter_record_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.CharField(default='REG823445', max_length=9, primary_key=True, serialize=False),
        ),
    ]
